# Generated by Django 6.0 on 2026-01-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_aichatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIChatMessage',
        ),
    ]
