# Generated by Django 6.0 on 2026-01-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_assessment_assessmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='max_marks',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
