# Generated by Django 6.0 on 2026-01-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_assessment_max_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
