# Generated by Django 6.0 on 2026-01-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_profile_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
